### ISSUE TITLE
Missing dependency 'alexsoft/curl'

### ISSUE THREAD

**Issue by eddiejaoude** [asakusuma/SugarCRM-REST-API-Wrapper-Class#31]
Error:
asakusuma/sugarcrm-wrapper dev-master requires alexsoft/curl 0.4.*@dev -> no matching package found

**Comment by kendantinio** [comment]
so how do we fix this? got same isses

**Comment by kendantinio** [comment]
okay lemme just answer this

The answer is just add @dev
This is METHOD ONE:
{
    "require": {
        "cartalyst/sentry": "2.0.*@dev"
    },
}

You can read more about minimum stability settings here.

An alternative is to set your minimum-stability to dev, but tell composer you want to use stable whenever possible:

This is METHOD TWO:

"minimum-stability": "dev",
"prefer-stable" : true

This basically means it will always use stable UNLESS there is no way to install a stable dependency, and therefore use dev.

Reference: http://stackoverflow.com/questions/23086204/composer-required-packages-with-differing-levels-of-minimum-stability

**Comment by kendantinio** [comment]
You can read more about minimum stability settings here. 
https://igor.io/2013/02/07/composer-stability-flags.html

**Comment by rustysamurai** [comment]
I am having the same issue, however, the github repo for it (linked above by mohsinrasool) is giving a 404. I have tweeted the developer, but no luck. Can anyone who has it already, upload it somewhere to download and put in manually?

**Comment by rustysamurai** [comment]
He replied, the repo was deleted. He suggested to use https://github.com/guzzle/guzzle instead if it helps anyone.

**Comment by eddiejaoude** [comment]
Guzzle is a gerat http client. Note, you would have to wrap the calls and manage the errors etc yourself.
